### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by sunnyujjawal** [emmanuelkehinde/TwittaSave-Web#2]
i uploaded the code but download function not working.
please help.

**Comment by emmanuelkehinde** [comment]
You need to add the app KEY and SECRET.

Simply create a new app on Twitter for Developers. Copy the KEY and SECRET and paste it in the script.

It should work.

**Comment by emmanuelkehinde** [comment]
Let me know if any other Issues​ arise.

Thanks.

**Comment by sunnyujjawal** [comment]
@emmanuelkehinde thanks
please guide in which file i have to add the KEY and SECRET

**Comment by emmanuelkehinde** [comment]
app.js file.

In cb.setConsumerKey()

**Comment by sunnyujjawal** [comment]
Key and secret added but download not working .. only circle keeps on revolving.
please check https://timesofmovie.com/twitter-video-downloader/

`$(function () {

// Enable Tooltip
    $('[data-toggle="tooltip"]').tooltip(); 


    var fetched=false;
    var cb = new Codebird;
    cb.setConsumerKey("[uLsbZ2BnlETAeYKeU640ZPoCe]", "[BhTdLLcX5wDe1zQTe7jXHk0SHu8D9HG3pyNt4QPzliqTJqpttf]");
    // var key = encodeURIComponent("QYaPv9WJcuWDDggISaFwqYomC");
    // var secret = encodeURIComponent("mhOqMLBKtK6Z7AhEFOuHd3cFWMB9KbSbe5fUKTu1LoyHaCkPsn");
    // var concat=key+":"+secret;
    //
    // // Create Base64 Object`

**Comment by emmanuelkehinde** [comment]
Sorry for that... Kindly remove the square bracket before and after the KEY and SECRET. It should work.

**Comment by sunnyujjawal** [comment]
Removed but not working... only circle keeps on revolving.

**Comment by emmanuelkehinde** [comment]
Kindly check your browser console for any error message.

**Comment by sunnyujjawal** [comment]
Here is the console screenshot:
https://image.prntscr.com/image/YSYye3_1QMKHTOjtDdtOTw.png

**Comment by sunnyujjawal** [comment]
It's working fine in Mozilla firefox..
Click on download button goes to new page to save gif or video

**Comment by emmanuelkehinde** [comment]
I think I know why there is an error. The website is hosted using firebase...so firebase added scripts.

**Comment by emmanuelkehinde** [comment]
So I will create a dev branch which you can use directly with no issues.

**Comment by emmanuelkehinde** [comment]
Thanks for pointing this out.

**Comment by sunnyujjawal** [comment]
Thanks
I will wait for the update.

**Comment by emmanuelkehinde** [comment]
I have added a dev branch.
It's tested okay.

**Comment by emmanuelkehinde** [comment]
You can checkout the dev branch...add the KEY and SECRET and test.
